# -*- coding: utf-8 -*-
"""DataVisualizationAssignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qB7Bp0G0yRc0L9q89-y6zs35rDHGj3jM
"""



# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip3 install matplotlib seaborn pandas

# For plotting the data
import matplotlib.pyplot as plt
import seaborn as sns
# For data manipultaion
import pandas as pd
# For scientific or mathematical computations
import numpy as np

import plotly.express as px

import plotly.express as px
import pandas as pd

df = pd.read_csv('haberman.csv')

df = pd.read_csv("haberman.csv",header=None, names = ['Age', 'Operation_year', 'Positive_lymph_nodes', 'Survived'])
df.head()

df.info()

"""Box Plot

"""

for column in df.columns[:-1]:
    sns.boxplot(x = 'Survived', y = column, data = df)
    plt.title("haberman data")
    plt.show()

"""There are 0 deaths before age 34 and there are 0 survivors after age 78
. there are many outliers in Positive lymph Nodes
. 50th percentile of Survived and not survied is same i.e. 1963
. 25th percentile and 50th percentile of positive node are overlapped at 0

**violinplot**
"""

for column in df.columns[:-1]:
    sns.violinplot(x = 'Survived', y = column, data = df)
    plt.title("haberman data")
    plt.show()

"""During Univariate Analysis Only Positive Lymph Nodes can be found dinguishable factor and that too with 100%. we will try to find some classification factors in bi-variate or multivariate analysis using Positive lymph nodes in focus."""